//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grocery_DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderId { get; set; }
        public int userId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
        public decimal total { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
